version: '3'

networks:
  fastrrr_databay:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - fastrrr_databay

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/www/html:delegated
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - fastrrr_databay

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - fastrrr_databay